---
- name: apt-get update
  apt: update_cache=yes

- name: set hostname
  lineinfile: dest=/etc/hostname regexp="^.*"  line='{{ inventory_hostname }}'
  notify: reload hostname
  
- name: change ipv4 hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv4.address}}" line="{{ ansible_default_ipv4.address}} {{ inventory_hostname }}"
  notify: restart networking

- name: change ipv6 hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv6.address}}" line="{{ ansible_default_ipv6.address}} {{ inventory_hostname }}"
  notify: restart networking

- name: Set up iptables rules
  copy: src=iptables.up.rules dest=/etc/iptables.up.rules
  notify: restart server
  
- name: Ensure iptables is loaded on startup by adding a command to interfaces file
  lineinfile: dest=/etc/network/interfaces insertafter="^iface lo inet loopback"  line="  pre-up iptables-restore < /etc/iptables.up.rules"
  



