---
- name: set hostname
  lineinfile: dest=/etc/hostname regexp="^.*"  line='{{ inventory_hostname }}'
  notify: reload hostname

- name: Add user so we can turn off root login
  user: name='{{ admin_user_name }}' shell=/bin/bash state=present  
  
- name: Add RSA key to the remote host for the admin user
  authorized_key: user='{{ admin_user_name }}' key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: add admin user to sudoers file
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{ admin_user_name }}' line='{{ admin_user_name }} ALL=(ALL) NOPASSWD:ALL'"

- name: adapt sshd config to block password and root logins
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart ssh
  
- name: Set up iptables rules
  copy: src=iptables.up.rules dest=/etc/iptables.up.rules
  notify: restart server
  
- name: Ensure iptables is loaded on startup by adding a command to interfaces file
  lineinfile: dest=/etc/network/interfaces insertafter="^iface lo inet loopback"  line="  pre-up iptables-restore < /etc/iptables.up.rules"
  



